-- AlterTable
ALTER TABLE `ticket` ADD COLUMN `directorApprovedAt` DATETIME(3) NULL,
    ADD COLUMN `directorApprovedById` INTEGER NULL,
    ADD COLUMN `secretaryApprovedAt` DATETIME(3) NULL,
    ADD COLUMN `secretaryApprovedById` INTEGER NULL,
    MODIFY `status` ENUM('PENDING', 'SECRETARY_APPROVED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `ticketstatushistory` MODIFY `fromStatus` ENUM('PENDING', 'SECRETARY_APPROVED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NULL,
    MODIFY `toStatus` ENUM('PENDING', 'SECRETARY_APPROVED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NOT NULL;
