-- AlterTable
ALTER TABLE `ticket` ADD COLUMN `adminAcknowledgedAt` DATETIME(3) NULL,
    ADD COLUMN `adminAcknowledgedById` INTEGER NULL,
    ADD COLUMN `dateToVisit` DATETIME(3) NULL,
    ADD COLUMN `headScheduledAt` DATETIME(3) NULL,
    ADD COLUMN `headScheduledById` INTEGER NULL,
    ADD COLUMN `monitorNotes` TEXT NULL,
    ADD COLUMN `monitoredAt` DATETIME(3) NULL,
    ADD COLUMN `monitoredById` INTEGER NULL,
    ADD COLUMN `recommendations` TEXT NULL,
    ADD COLUMN `targetCompletionDate` DATETIME(3) NULL,
    MODIFY `status` ENUM('FOR_REVIEW', 'REVIEWED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'PENDING_ACKNOWLEDGMENT', 'SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NOT NULL DEFAULT 'FOR_REVIEW';

-- AlterTable
ALTER TABLE `ticketstatushistory` MODIFY `fromStatus` ENUM('FOR_REVIEW', 'REVIEWED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'PENDING_ACKNOWLEDGMENT', 'SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NULL,
    MODIFY `toStatus` ENUM('FOR_REVIEW', 'REVIEWED', 'DIRECTOR_APPROVED', 'ASSIGNED', 'PENDING_ACKNOWLEDGMENT', 'SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED') NOT NULL;
